---
format:
  pdf:
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
    keep-tex: true
    header-includes:
      - \usepackage{multicol}
      - \usepackage{xcolor}
---

ISSN# 2332-4503

\pagenumbering{roman}

## About the Journal

The Journal of Kinesiology & Wellness (JKW) is an anonymous peer-reviewed online journal that covers issues in physical education, physical activity & health promotion, wellness, biomechanics, motor behavior, exercise physiology, sport, and dance. The JKW is a publication of the Western Society for Kinesiology and Wellness (WSKW).

The JKW does not charge a publication fee, and the journal has an open-access policy, meaning all articles are freely available online for anyone to read, download, and share. The JKW aims to promote scholarly communication and disseminate high-quality knowledge to the academic community and the public.

Accepted papers are published on a rolling basis. Papers are published under two sections:

- The Articles section consists of scholarly papers based on original research (experimental, descriptive, historical, or philosophical) and the invited John Massengale Paper[^1].
- The Articles (Student Scholarship) section is reserved for scholarly papers based on original research (experimental, descriptive, historical, or philosophical) in which a student (undergraduate or graduate) is the lead author.

The full volume, published each January, includes the WSKW Chronicles, which include post-conference proceedings, such as conference abstracts. 

[^1]: The John Massengale Paper is an exclusive publication written by a distinguished scholar. Contact us to suggest an author, or nominate yourself. 

## Open Access

This is an open-access journal, which means that all content is freely available without charge to the user or his/her institution. Users are allowed to read, download, copy, distribute, print, search, or link to the full texts of the articles or use them for any other lawful purpose without asking the publisher's or the author's prior permission. 

## Copyrights

The authors hold the copyright of the published content. 

## Repository Policy

Authors can deposit all versions of their work, including submitted, accepted, and published versions, in their preferred institutional or other repository.

## Journal Qualification

Google Scholar h index (2012-2023): 5  
Google Scholar h index (since 2019): 4

Visit the JKW website for more information:  
https://jkw.wskw.org/index.php/jkw/about

Note to authors: Manuscripts can be submitted through the JKW website:  
https://jkw.wskw.org/index.php/jkw/submission

Questions can be directed to Dr. Jeff Bernard, Editor-in-Chief at jbernard1@csustan.edu.

\newpage

\begin{center}
    \textbf{\Large \textcolor{blue!60!black}{Journal of Kinesiology and Wellness}} \\
    \vspace{0.2cm}
    \textbf{A Publication of the Western Society for Kinesiology and Wellness}
\end{center}

\vspace{0.5cm}

\begin{center}
    Cathy Inouye \\
    \textit{California State University, East Bay} \\
    \textbf{WSKW Executive Director}
\end{center}

\vspace{0.3cm}

\begin{multicols}{2}
    \begin{center}
        Jeff Bernard, Ph.D. \\
        \textit{California State University, Stanislaus} \\
        \textbf{JKW Editor-in-Chief}
    \end{center}
    
    \columnbreak
    
    \begin{center}
        Ovande Furtado, Jr., Ph.D. \\
        \textit{California State University, Northridge} \\
        \textbf{Associate Editor}
    \end{center}
\end{multicols}

\vspace{0.5cm}

\begin{center}
    \textbf{JKW Editorial Board}
\end{center}

\begin{multicols}{2}
    \begin{center}
        Seung Ho Chang, Ph.D. \\
        \textit{San Jose State University}
        
        \vspace{0.2cm}
        
        Gioella Chaparro, Ph.D. \\
        \textit{California State University, Dominguez Hills}
        
        \vspace{0.2cm}
        
        Min Kim, Ph.D. \\
        \textit{Sam Houston State University}
    \end{center}
    
    \columnbreak
    
    \begin{center}
        Jongil Lim, Ph.D. \\
        \textit{Texas A\&M University- San Antonio}
        
        \vspace{0.2cm}
        
        Laura Robinson-Doyle, M.S. \\
        \textit{Southern Methodist University}
        
        \vspace{0.2cm}
        
        Heather Van Mullem, Ph.D. \\
        \textit{Lewis-Clark State College}
    \end{center}
\end{multicols}

\vspace{0.5cm}

\begin{center}
    \textbf{Reviewers for Vol 11, No 1, 2022- Annual Edition}
\end{center}

\begin{multicols}{2}
    Ovande Furtado, \textit{California State University, Northridge} \\
    Seung Ho Chang, \textit{San Jose State University} \\
    Jeff Bernard, \textit{California State University, Stanislaus} \\
    Jongil Lim, \textit{Texas A\&M University -- San Antonio} \\
    Gioella Chaparro, \textit{California State University, Dominquez Hills} \\
    Laura Robinson-Doyle, \textit{Southern Methodist University} \\
    Heather Van Mullem, \textit{Lewis-Clark State College} \\
    Min Kim, \textit{Sam Houston State University} \\
    Andrea Ednie, \textit{University of Wisconsin- Whitewater} \\
    Shirley Reekie, \textit{San Jose State University}
\end{multicols}

\vspace{0.3cm}

\begin{center}
    \textbf{Reviewers for Vol 11, No 2, 2022- Student Edition}
\end{center}

\begin{center}
    Ovande Furtado, \textit{California State University, Northridge} \\
    Seung Ho Chang, \textit{San Jose State University} \\
    Jeff Bernard, \textit{California State University, Stanislaus} \\
    Gioella Chaparro, \textit{California State University, Dominquez Hills} \\
    Jongil Lim, \textit{Texas A\&M University -- San Antonio}
\end{center}

