---
title: "Article Edition"
format:
  pdf:
    documentclass: scrartcl
    classoption:
      - numbers=noendperiod
      - DIV=15
    variable:
      geometry: "margin=0cm"
    header-includes:
      - \usepackage{pdfpages}
---

\pagenumbering{roman}
\includepdf[pages=-]{annual-ed/preface.pdf}

\newpage
\tableofcontents

\newpage
\pagenumbering{arabic}
\setcounter{page}{1}

\addcontentsline{toc}{section}{Articles}

\includepdf[pages=-,addtotoc={1,subsection,1,{Kinematics comparison of squat (2D vs 3D analysis) for remote learning – pilot study},art1}]{annual-ed/pdfs/articles/01-23-jkw-huang22-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Bicycle coalitions and universities prioritization of equity: why and why not? A shift towards more equitable opportunities},art2}]{annual-ed/pdfs/articles/15-24-dzieniszewski-etal-22-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Citations in Google Scholar profiles by Kinesiology subdiscipline},art3}]{annual-ed/pdfs/articles/25-33-Knudson-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{A model for return to training and competition during ongoing pandemic concerns},art4}]{annual-ed/pdfs/articles/34-45-telles-langdon-pub.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{A Comparison of health locus of control and physical activity among Seventh-day Adventists and non-Seventh-day Adventists},art5}]{annual-ed/pdfs/articles/46-55-Feiler_Ngo-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Exploring learning outcomes among undergraduate kinesiology students in response to an inclusive physical activity promotion message assignment},art6}]{annual-ed/pdfs/articles/56_81_Ross_Thomas-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Research quality; a collective endeavor},art7}]{annual-ed/pdfs/articles/82.93-shifflett-2022-final.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Suitability: a longitudinal study of adult-focused physical activity promotion web articles},art8}]{annual-ed/pdfs/articles/94-106-thomas-etal-2022.pdf}

\includepdf[pages=-,addtotoc={1,subsection,1,{Local heating and cooling with isometric exercise training as a strategy to improve size and performance},art9}]{annual-ed/pdfs/articles/107-117-feng-etal-final.pdf}
