# JKW Full Volume — 2023 (Vol 12, No 1)

year: 2023
volume: 12
issue: 1

cover_image: cover-2023.png

output_file: JKW_2023_Full_Volume.pdf

articles:
  - file: sources/manuscripts/articles/Eastman_etal_2023.pdf
    title: "Acute Beetroot Supplementation May Improve Blood Pressure But Not Exercise Economy in Female Masters Swimmers"

  - file: sources/manuscripts/articles/JKW+23-118.pdf
    title: "Daily Heart Rate Variability is Higher in Regular Exercisers Versus Matched Non-Exercisers with Similar Chronic Stressor Profiles During the COVID-19 Pandemic"

  - file: sources/manuscripts/articles/jkw_23_126.pdf
    title: "Explicit Weight Bias Concerns in the Fitness Industry: A Quantitative Analysis"

  - file: sources/manuscripts/articles/marchetti_23.pdf
    title: "Acute Effects of Different Number of Sets and Non-Equalized Volume on Muscle Thickness, Peak Force, and Physical Performance in Recreationally-Trained Participants"

  - file: sources/manuscripts/articles/125_Rhea_etall_final.pdf
    title: "Adult Outdoor Play Preferences: Why Nature Space Design Matters"

  - file: sources/manuscripts/articles/JKW-23-132-final.pdf
    title: "Effects of Positive and Negative Self-Talk on Balance and Postural Sway in College Students"

  - file: sources/manuscripts/articles/JKW-23-138.pdf
    title: "Examining the Relationship Between BMI, Sex, and Fundamental Movement Skill Performance in Low-Income Rural Children"

chronicles:
  file: chronicles/2023_WSKW_Chronicles.pdf
  title: "WSKW Chronicles: 2023 WSKW Annual Conference"
